import React, { useState } from 'react';
import { Search, Sparkles } from 'lucide-react';
import { searchRaiku } from '../services/geminiService';

const Hero: React.FC = () => {
  const [query, setQuery] = useState('');
  const [response, setResponse] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!query.trim()) return;

    setLoading(true);
    setResponse(null);
    
    try {
      const res = await searchRaiku(query);
      setResponse(res);
    } catch (err) {
      setResponse("Sorry, something went wrong.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <section id="hero" className="relative min-h-screen flex flex-col justify-center items-center px-4 pt-20 overflow-hidden">
      {/* Background Gradient Mesh */}
      <div className="absolute top-0 left-0 w-full h-full overflow-hidden -z-10">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-raiku-primary/20 rounded-full blur-[100px]" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-raiku-secondary/20 rounded-full blur-[100px]" />
      </div>

      <div className="text-center max-w-4xl mx-auto">
        <div className="inline-flex items-center px-3 py-1 rounded-full border border-white/10 bg-white/5 mb-6 backdrop-blur-sm">
          <span className="text-raiku-secondary text-xs font-bold uppercase tracking-wider">chrollo6940's hub</span>
        </div>
        
        <h1 className="text-5xl md:text-7xl font-bold mb-6 bg-clip-text text-transparent bg-gradient-to-r from-white via-gray-200 to-gray-500">
          Raiku
        </h1>
        <p className="text-2xl md:text-3xl text-gray-400 mb-8 font-light">
          Deterministic Scheduling for Solana
        </p>

        {/* AI Search Box */}
        <div className="w-full max-w-2xl mx-auto relative group">
          <div className="absolute -inset-1 bg-gradient-to-r from-raiku-primary to-raiku-secondary rounded-lg blur opacity-25 group-hover:opacity-50 transition duration-1000"></div>
          <form onSubmit={handleSearch} className="relative">
            <input
              type="text"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Ask AI about Raiku (e.g., 'What is AOT scheduling?')"
              className="w-full bg-raiku-card border border-white/10 rounded-lg py-4 pl-12 pr-4 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-raiku-primary/50 transition-all shadow-xl"
            />
            <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-500" size={20} />
            <button 
              type="submit" 
              disabled={loading}
              className="absolute right-2 top-1/2 transform -translate-y-1/2 bg-white/10 hover:bg-white/20 text-white p-2 rounded-md transition-colors"
            >
              {loading ? (
                <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
              ) : (
                <Sparkles size={18} />
              )}
            </button>
          </form>
        </div>

        {/* AI Response Card */}
        {response && (
          <div className="mt-6 w-full max-w-2xl mx-auto bg-raiku-card/90 backdrop-blur-md border border-white/10 rounded-lg p-6 text-left shadow-2xl animate-fade-in-up">
            <div className="flex items-start gap-3">
              <Sparkles className="text-raiku-primary mt-1 shrink-0" size={20} />
              <div>
                <p className="text-gray-200 leading-relaxed text-sm md:text-base">{response}</p>
                <p className="text-xs text-gray-600 mt-2">Generated by Gemini • Grounded in Raiku Docs</p>
              </div>
            </div>
          </div>
        )}
      </div>
    </section>
  );
};

export default Hero;